---
title: "LoL Gender Bias"
format: html
---

Prepping Data

Load json file

```{r}
library(tidyverse)
library(janitor)
library(vcd)
library(effectsize)
library(jsonlite)

url <- "https://gist.githubusercontent.com/Kerrders/0067d88dfd982c272e20dcb496f4dbc7/raw/723fd605b15a4d84bafd82cbb5d352e523349308/champions.json"

# Read JSON directly from URL into an R object
champ_raw <- fromJSON(url)

# If it's already a data frame, great; otherwise coerce if needed
champ_df <- as.data.frame(champ_raw)

# Quick check
str(champ_df)
head(champ_df)


```

Save json and clean up lanes

```{r}
#champ_df |> 
#  select(name, title, resource, genre, skinCount, 
#gender, attackType, releaseDate, region, lane) |>
#  write_csv(file = "lol_gender_lanes_patch16.2.csv")
```

Read in cleaned up data
```{r}
lol_genders <- read_csv("iramler/lol_genderbias/lol_gender_lanes_patch16.2.csv")
```

Investigate the data to familiarize yourself with it. 

Univariate Tables

```{r}
count(lol_genders,gender)
```







```{r}
tab_df <- tabyl(champ_df|> filter(gender != "divers"), gender, lane)
tab_df
```

Find those with multiple lanes.

```{r}
champ_df|> filter(gender != "divers") |> 
  filter(str_detect(lane, ",") | is.na(lane) ) |> 
  select(name, lane) |> write_csv(file = "lol_multilane_champs.csv")
```

For now jus use the clean one

```{r}
clean_df <- champ_df|> filter(gender != "divers") |> 
  filter(str_detect(lane, ",", negate = TRUE) & !is.na(lane) )

```


```{r}
tab_df <- with(clean_df, table(gender, lane))
tab_df
```


```{r}
mosaic(t(tab_df), shade = TRUE, legend = TRUE, main = "Mosaic plot")
```


```{r}
chisq.test(tab_df, simulate.p.value = TRUE, B = 5000)
```

