---
title: "cleaningmorekfdata"
format: html
---

```{r}
#| message: false
#| warning: false

# Loading the libraries in:
library(tidyverse)
library(ggplot2)
library(stargazer)
```



```{r}
kf_8 <- read.csv("8kf.csv")

head(kf_8, 25)
```



```{r}
first_step<- kf_8 |> separate_wider_regex(Form, c(Sex = "^.", Form = ".*")) |> separate_wider_regex(Form, c(delete = "^[^G]*", Group = ".*")) |> select (-delete)

```


```{r}

eightyearkungfu <- read.csv("working8thkungfu.csv")

kungfu_8 <- eightyearkungfu |> separate_wider_regex(Group, c(Group = "^[^ ]+ [^ ]+", Form = ".*")) |> separate_wider_regex(Form, c(Delete = "^[^a-zA-Z]*", Form = ".*")) |> select (-Delete)


write.csv(kungfu_8, "kungfu_8.csv")
```



```{r}
ninthyear<- read.csv("9kf.csv")

working <- ninthyear |> separate_wider_regex(Form, c(Delete = "^[^a-zA-Z]*", Form = ".*")) |> select (-Delete) |> separate_wider_regex(Form, c(Sex = "^.", Form = ".*")) |> separate_wider_regex(Form, c(Form = ".*(?=G[^G]*$)", Group = ".*")) |> separate_wider_regex(Form, c(Delete = "^[^s]*s", Form = ".*")) |> select (-Delete) |> separate_wider_regex(Form, c(Delete = "^[^a-zA-Z]*", Form = ".*")) |> select (-Delete)

write.csv(working, "kungfu_9.csv")

```



```{r}

sevenyear <- read.csv("7kf.csv")

sevenyearworking <- sevenyear |> separate_wider_regex(Form, c(Delete = "^[^MW]*", Form = ".*")) |> select (-Delete) |> separate_wider_regex(Form, c(Sex = "^[^G]*", Form = ".*")) |> 
  separate_wider_regex(Form, c(Group = "^[^A-Z]*[A-Z][^A-Z]*[A-Z]",
                               Form = ".*"), too_few = "align_start") |> na.omit(Form) |> separate_wider_regex(Sex, c(Sex = "^.", Delete = ".*")) |> select (-Delete) 

write.csv(sevenyearworking, "kungfu_7.csv")

```

