---
title: "Kung Fu"
subtitle: Complete Linkage Hierarchical Clustering
author: Elena Cortina Pino
date: February 19, 2026
format: html
---


# **This is the arranged document that consolidates information from `kungfu.qmd` and `cleaningmorekfdata.qmd` to serve as the Guide Quarto for the final Kung Fu Module**


### Loading libraries

```{r}
#| message: false
#| warning: false

# Loading the libraries in:
library(tidyverse)
library(VIM)
library(ggplot2)
library(gplots)
library(pheatmap)
library("RColorBrewer")
library(grid)
```



### Loading Data


```{r}
# read `matrix_kf10.csv` which comes from many many many iterations of dplyr code

matrix_kf10 <- read.csv("mat_10kf.csv") |> select(-A) |> select(-`F`)
```



### Plot 

```{r}
#| label: heatmap
#| warning: false

# selecting OUT the non-numeric columns in the data frame
mat <- as.matrix(matrix_kf10[,-1])
# chooses which column from the dataset to use for the row names
rownames(mat) <- as.character(matrix_kf10$Forms)
# setting the color palette to blue, white, red. intentionality.
col<- colorRampPalette(c("#2565AD", "white", "#E34825"))(256)
#trying to get thicker dendrogram lines

# using pheatmap to create the clustered heatmap
heatmap <- pheatmap(
  mat,
  scale = "row", # character indicating if the values should be centered and scaled in either the row direction or the column direction, or none.
  clustering_distance_rows = 'euclidean',
  #clustering_distance_cols = 'euclidean',
  clustering_method = "complete",
  cluster_rows = T,
  cluster_cols = F,
  show_colnames = TRUE, 
  show_rownames = TRUE,
  display_numbers = T,
  cellwidth = NA, # adjust export size to account for print needs
  cellheight = NA, 
  angle_col = 0,
  number_color = "#303030",
  border_color = "#303030", 
  main = "Complete Linkage Clustered Heatmap with Dendrograms",
  cutree_rows = 6, # number of major clusters of forms
  color = col,
  legend = T,
  legend_labels = "Z-scores",
  legend_position = "top")


# MOVE LEGEND TO TOP
```

