---
title: "World Kung Fu Championship - Data Scraping, Cleaning and Visualizing"
subtitle: "Method for scraping raw data from pdf document into usable table form csv document with Excel, R code, Regex and Notepad++"
author:
  - name: "Elena Cortina Pino"
    url: https://www.linkedin.com/in/elenacortina
description: "This module goes through the process of scraping and cleaning raw data from the International Wushu Federation Result Books from the World Kung Fu Championships available online from the 7th edition through the 10th edition."
lightbox: true
format: 
  html:
    embed-resources: false
categories:
  - Data scraping
  - Data cleaning
  - Regex
  - dplyr
  - Notepad++
---

## Background

Data by years:

7th:\

[Reference document](https://www.iwuf.org/wp-content/uploads/2018/12/7th-World-Kungfu-Championships-Regulations.pdf)

The 7th edition of the competition divided age categories in only 5 groups.


8th:\
[The 8th World Kungfu Championships in Emeishan, China 2019](https://iwuf.org/wp-content/uploads/2019/06/8th-WKFC-Program-Book-International-Group.pdf)

9th:\
[The 8th World Kungfu Championships in Emeishan, China 2023](https://www.iwuf.org/wp-content/uploads/2023/09/9th-WKFC-Results-Book-境外组.pdf)



##### Variables

<details>

<summary><b>Variable Descriptions</b></summary>

| Variable | Description                                |
|----------|--------------------------------------------|
| Sex      | Sex of athlete                             |
| Form     | Kung fu form the athlete competed in       |
| Rank     | Rank of athlete in the event               |
| Team     | Country the athlete is representing        |
| Athlete  | Athlete's name                             |
| Score    | Numerical score out of 10 possible points  |
| Remark   | Prize awarded based on the score and event |

</details>



### Programs

#### Excel


#### RStudio

Within the RStudio portion of the process we utilize a significant amount of reg-ex knowledge. There is a vast selection of good AI-backed regex libraries online that provide what we would describe as "english to regex" translations.


We can say it in a few different ways, also navigating the limitations R has to interpret `\s` and `\S`.

**Example**

**_"International Women's Group C Traditional Chen Style Taijiquan"_**

We need to separate this information, which currently appears all together as a single string in a cell after the data was scraped, into 3 different columns:\
1. The sex of the athlete\
2. The Age group they compete in\
3. They kung fu form they compete in\

There are many good approaches to go about successfully and efficiently completing this task. We can list a few: (evaluating all possible approaches before start redacting up code is a good habit to get into. Think of this process as an algorithm. There can be many algorithms that are equally useful in a situation, though one of them might be discerningly more efficient...)

1. We can first select the `W` in `Women's` to fetch the sex of the player. Consider the natur eof the data as it changes across rows. That`W` can also be an `M`. That `W`/`M` is sufficient information to check that box. That step leaves us with `W` or `M` in a column and everything else in another column (starting after the `W` we just took away). Let's name the sex column `Sex` and the resting can have any name... Let's choose `Working` since we have some more splitting to do.\
\
Then, we can get the age group (which goes from `A-F`) by selecting the first capital letter after the second space. That leaves us with another new column. Lets name it `Group` the rest can be `Form`.\
\
These iterations leave us with a few spaces to delete here and there. The approach we've takes is to be very clear about the information we keep and decide to remove, so it might seem longer than one might originally conceive the task to be...\
\
\

2. Using the `separate` function from the `tidyr` package, our strategy changes. Here we can use the structure of the string as an advantage to separate it into three columns:
  2. 1  Use the middle element of the string as the separating element that the function `separate` requires.
  In this case, we can use the `Group` as the separator between our information of the `sex` and the `form`. This then becomes an easier cleanup once we have all three parts on their own columns.\
  2.2 Once separated, we still have to cleanup the inevitable spaces, extra words and, if present, punctuation.\

3. ? Come up with another inventive way to separate the string as an exercise...



#### Notepad++

This app has a lot of helpful functionalities that helped us clean this data quickly without having to start another file on R or Excel and to keep the structure of the data integral.

In multiple iterations of the cleanup process, and simply because this deals with so many strings I basically got inventive and resourceful so I used what I was more inclined to use and knew would solve the issue faster... Some people wouldn't like this....


We're in Excel, then copy the entire column ,paste it into Notepad++, clean up what needs to be cleaned up quickly, and move the column back to the excel exactly where it was without loosing observations or messing with the order.


Some of the Notepad++ functionalities that came in extra helpful (more than they would have been in Excel) are:
1. Line operations
2. Blank operations
3. Find and replace all occurrences of a string or characters.

We recognize that these are all possible from within R or Excel.... But because these are strings, it makes sense to be tactful and resourceful in the tools we use to work on cleaning the (broader) string.

For example: in Notepad++ we can Ctrl + Alt and select down the same line of text down to the last line and simultaneously edit from that position of the line in all lines at the same time. That can't be done in Excel.


Using find and replace in Excel is troublesome for a few reasons, the main one being that it's not always quite accurate. From the Excel toolkit , we used the filtering and the sorting to be able to identify `NA` observations in Missing scores, to filter forms into alphabetical order to identify duplicate forms that were registered in the result book with different ways to say the same thing.. and to clear some columns while we were at it, such as the bib number, the group events and the Rank.


